name: peglit-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - viennarna=2.6.4
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - python-levenshtein
  - pip
  - pip:
    - streamlit==1.35.0
